# Generated by Django 6.0.4 on 2026-05-06 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('lesson_plan', 'Lesson Plan'), ('assessment', 'Assessment'), ('content', 'Content Generator'), ('tutor', 'AI Tutor'), ('teacher_agent', 'Teacher Agent'), ('admin_agent', 'Admin Agent'), ('page_view', 'Page View')], max_length=30)),
                ('page', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='schools.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feature', 'created_at'], name='analytics_u_feature_16da0c_idx'), models.Index(fields=['school', 'created_at'], name='analytics_u_school__0922d3_idx')],
            },
        ),
    ]
